# include:
#  # Import template CI/CD node   
#   - project: 'omnichannel/integration-cross/devops/templates-gitlab-ci/templates-node/azure-static-web-apps'
#     ref: main
#     file: '.gitlab-ci-template-node-static-web-app.yml'

include:
# Build -Dependencies
- project: omnichannel/integration-cross/devops/templates/build/nodejs
  ref: main
  file: gitlab-ci-template.yml


stages:
  - create-variables-env
  - build
  - deploy

create-variables-env:
  extends: .create_variables

build:
  extends: .npm_install_vue
  retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
  only:
    - develop
    - uat
    - main
  
  needs:
   - create-variables-env


deploy-dev:
  stage: deploy
  image: node:lts-buster
  variables:
    API_TOKEN: "$DEV_DEPLOYMENT_TOKEN"
    APP_PATH: "$CI_PROJECT_DIR"
    OUTPUT_PATH: '$CI_PROJECT_DIR/dist'
    SWA_CLI_DEPLOY_ENV: "Production"
    #SWA_RUNTIME_CONFIG: staticwebapp.config.json
    #CONFIG_FILE_LOCATION: "swa-cli.config.json"
  
  # needs:
  #  - [build,create-variables-dev]
    
  before_script:
    - npm install -g @azure/static-web-apps-cli 

  script:
    - swa deploy --verbose=silly ./dist -d $API_TOKEN  -w ./  --env $SWA_CLI_DEPLOY_ENV #--swa-config-location ./

  only:
    - develop


